### ISSUE TITLE
CLE Lab: Library Assessment workflow w/ LabChip GX Touch Pipeline

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#211]
http://sandbox5.wucon.wustl.edu:11702/#/builders/workflows/details/db065ace-287c-423e-be56-4f0e4f0d78ec

Need LabChip GX Touch pipeline ingest programming for Ingest LabChip GX Data File

[Example GX File 2022-06-02_12-23-33_Andy_TCP_201_WellTable.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/11223987/Example.GX.File.2022-06-02_12-23-33_Andy_TCP_201_WellTable.csv)

Show all columns on ingest from CSV.

**Comment by billtell** [comment]
- 'CLE Lab: Ingest LabChip GX Data File'
  - 'CLE Lab: Library Assessment QC'
  - 'CLE Lab: Library Assessment Reagent Lot Tracking'
  - 'DNA Lab: Next Step'

to 

  - CLE Lab: Library Assessment
  - CLE Lab: Library Assessment Review

**Comment by billtell** [comment]
```
  - Library Volume (µl):
      instructions: Enter the measured volume for the libraries. This value will be
        the same for each sample. Make sure this is done after 2uL is removed for
        the GX dilution tray.
      required: true
      rule: numeric
      value: This value will be the same for all samples. Need an expression to populate
        same value for all samples.
```

Subtract 2 ul from `Volume (µl)`

**Comment by billtell** [comment]
Instead of `Fail Reason` column use a `Exception` column to track QC Fails in Assessment areas.

aka: Determine best way to track Exceptions

**Comment by billtell** [comment]
Well Position values? Dimensions?

**Comment by billtell** [comment]
```
Fast-forward
 content/inventory/entity_types.yml                                                                       |  10 +++---
 content/pipelines/cle_library_assessment.yml                                                             |  25 +++++++++++++
 content/pipelines/scripts/cle_dna_dilution_assign_well.py                                                |   4 +--
 content/pipelines/scripts/cle_library_assessment.py                                                      |   0
 content/protocols/cle_dna_dilution_setup_protocol.yml                                                    |   4 +--
 content/protocols/cle_ingest_labchip_gx_data_file_protocol.yml                                           |  35 -------------------
 content/protocols/cle_library_assessment_protocol.yml                                                    | 101 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 content/protocols/cle_library_assessment_reagent_lot_tracking_protocol.yml                               |  57 ------------------------------
 content/protocols/{cle_library_assessment_qc_protocol.yml => cle_library_assessment_review_protocol.yml} |  30 ++++++++--------
 content/workflows/cle_dna_dilution_workflow.yml                                                          |   2 +-
 content/workflows/cle_library_assessment_workflow.yml                                                    |  35 ++++++++-----------
 roles/seed/content.yaml                                                                                  |  14 +++++---
 12 files changed, 173 insertions(+), 144 deletions(-)
 create mode 100644 content/pipelines/cle_library_assessment.yml
 create mode 100644 content/pipelines/scripts/cle_library_assessment.py
 delete mode 100644 content/protocols/cle_ingest_labchip_gx_data_file_protocol.yml
 create mode 100644 content/protocols/cle_library_assessment_protocol.yml
 delete mode 100644 content/protocols/cle_library_assessment_reagent_lot_tracking_protocol.yml
 rename content/protocols/{cle_library_assessment_qc_protocol.yml => cle_library_assessment_review_protocol.yml} (87%)
```

**Comment by billtell** [comment]
Remove `Dilution Factor` column.  Always assume a 1:20 dilution.

**Comment by billtell** [comment]
- [x] Make qubit file indexed on `Accession Number`, not order

**Comment by billtell** [comment]
- Need QC Thresholds for Library Assessment.

**Comment by billtell** [comment]
![Image](https://github.com/user-attachments/assets/bbdfd3e8-4202-4503-a297-d234ec873d1d)
![Image](https://github.com/user-attachments/assets/0ee8d086-86e7-4314-86ae-fba6aa0e7539)

**Comment by billtell** [comment]
- [x] subtract 2 from library volume and update entity

**Comment by billtell** [comment]
### Dec. 3rd Qeustions:

1.  Assays not included in table :  - UDN  - cDNA Exome - ChromoSeq  - cGS
- udn , cDNA Exome don't get assessed. , whole-genome samples won't get assessed
3. Library Size: FFPE/buccal swab vs. fresh/frozen
4. Gel Image - = unrequired.  done outside of ESP
5. gx File - 'Out of Range' or set to 0? -set to 0

**Comment by billtell** [comment]
### Dec.16th Questions
- Gx File - always csv or other formats possible
- Dilution Calculation - (for 1:20) sheet needs to perform that? outside of esp? done in library construction?
- Use`Well Label` or `Sample Name` - if Sample Name ?= Accession Number probably
- Need any other columns in Setup protocol? - like GX `Plate Name`-> format = `2022-06-02_12-23-33_Andy_TCP_201`
- UDN volume range.
- Does 4 reactions on QIACube meet requirements for everything but UDN?
- This whole section for speciment assessment:
> Any blood or bone marrow specimen with less than 750ng should get another extraction in case we need more DNA. (Any blood or marrow that is both MyeloSeq and ChromoSeq will get another extraction if it has less than 1000ng)
May need to come up with an "aliquot status" column during accessioning or assessment. If status = true, the yield must also be greater than the amount required for NGS and aliquot.

**Comment by billtell** [comment]
Adding concentration QC for Specimen Assessment (#423) - range for all assay types = 0.2 - 120 ng/µl

**Comment by billtell** [comment]
```
Fast-forward
 content/inventory/entity_types.yml                           |   2 +-
 content/pipelines/scripts/cle_library_assessment.py          | 153 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 content/pipelines/scripts/cle_specimen_assessment.py         |  64 +++++++++++++++++++++++++++++++++++++++++--------------
 content/protocols/cle_library_assessment_protocol.yml        |  33 +++++++++++++++++------------
 content/protocols/cle_library_assessment_review_protocol.yml |  95 ++++++++++++++++++++++++++++++++++------------------------------------------------
 content/protocols/cle_specimen_assessment_protocol.yml       |  20 ++----------------
 6 files changed, 262 insertions(+), 105 deletions(-)
```

**Comment by billtell** [comment]
- [x] Adding soft limits to Review protocol for Yield, Volume and Size
> Yield and Size are assay and sample type specific.  Setting to the most common range for right now.

**Comment by billtell** [comment]
Dilution factor fixed to multiply concentration by 20, not 0.05.

**Comment by abohanno** [comment]
Received the following error when I ran the pipeline script error on 2/3/25:

Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/cle_library_assessment.py", line 152, in <module>
    assessed_data = assess_pass_fail(ingest_protocol, gx_file_dict)
  File "/opt/l7esp/data/content/pipelines/scripts/cle_library_assessment.py", line 76, in assess_pass_fail
    _concentration = gx_file_dict[sample_id]['Region[200-600] Conc. (ng/ul)']
KeyError: 'ACC003'
{
 "units": "ms"
 "approximate_execution_time": 1084.123759
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["GET /api/sample_sheets/:uuid/bulk", 1, 303.83561, 303.83561, 303.83561, 303.83561, 1]
  ["GET /api/sample_sheets/:uuid", 1, 275.616086, 275.616086, 275.616086, 275.616086, 1]
  ["GET /api/files", 1, 108.991343, 108.991343, 108.991343, 108.991343, 1]
 ]
}

**Comment by abohanno** [comment]
figured this out. It is looking to match the accession number with the "sample name" column in the GX well table file. We don't have an easy way to do this. I think it would be best to key this off of the "well label" column. This should always match up. A01 in the library plate will always be A01 in the GX plate.
