### ISSUE TITLE
Seq Lab:  Final Ingest Template Update/Debug Ingest Script Errors

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#300]
Ingest Seq Receive Library script has errors: 

Possible spreadsheet error:
/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/seq_receive_library_pools.py", line 95, in <module>
    keys, values = zip(*df_dict.items())
ValueError: not enough values to unpack (expected 2, got 0)

Not sure: 
/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/l7esp/data/extensions/client/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/l7esp/data/extensions/client/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/l7esp/data/content/pipelines/scripts/seq_receive_library.py", line 20, in data_update
    for field, value in d_dict.items():
AttributeError: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/seq_receive_library.py", line 82, in <module>
    ebase.SESSION.put('/api/samples', json={'samples': payload})
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/esp/base.py", line 245, in _
    return func(self, endpoint, **kwargs)
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/esp/base.py", line 212, in _
    raise AssertionError(
AssertionError: Response from server (400) different from expected (200, 201, 202)

SERVER ERROR: Required 'uuid' in request missing

**Comment by LMT337** [comment]
Failed experiment: 
Worksheet: SR002125_Colonna_3v3.1_GEX_080723_New
SEQ Lab: Receive Library

**Comment by LMT337** [comment]
Pool ingest, should assign for 
Pool Concentration (ng/µl)	Pool Molarity (nM)	Total Volume of Pool (µl) Average Size (bp)
0.47	1.365	500
NO MATH
Pool Ingest, do not use: 
Library Concentration (ng/µl)	Library Molarity (nM)	Volume (µl)
Pool Template will have: 
Pool Concentration (ng/µl)	Pool Molarity (nM)	Total Volume of Pool (µl)
Library Template will have: 
Library Concentration (ng/µl)	Library Molarity (nM)	Volume (µl)

10 new fields for CRM billing file, will need to add them to ESP ingest and Entites if field does not exist.

**Comment by LMT337** [comment]
CRM Import files from Jen Friday 9/1: 


[Ingest_Template_Libraries_v2.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/12516796/Ingest_Template_Libraries_v2.xlsx)
[10XGenomics_Library_SampleSheet.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/12516797/10XGenomics_Library_SampleSheet.xlsx)
[10XGenomics_PooledLibraries_SampleSheet.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/12516798/10XGenomics_PooledLibraries_SampleSheet.xlsx)
[Ingest_Template_Pools_v2.xlsx](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/12516799/Ingest_Template_Pools_v2.xlsx)

**Comment by LMT337** [comment]
Updated Ingest file mappings: 
p={
   'Pool Name': 'Pool Name',
    'Pool Concentration (ng/µl)': 'Client Assessed Concentration (ng/µl)',
    'Pool Molarity (nM)': 'Client Assessed Molarity (nM)',
    'Pool Ave Size (bp)': 'Average Library Size (bp)',
    'Total Volume of Pool (µl)': 'Client Assessed Volume (µl)',
    'Targeted read-pairs for Pool (millions)': 'Requested Number of Reads (M)',
    'Sample Name': 'Sample Name',
    'Species': 'Species',
    'Library Type': 'Library Type',
    'Index1 or Pair Name': 'Index Name',
    'Index2 Name': 'i5 index Name',
    'i7 (Index 1) Sequence': 'i7 Index Sequence',
    'i5 (Index 2)_workflow_a': 'i5 Index Sequence',
    'Tube Label or External Barcode': '',
    '2D Rack Holder': '2D Barcode',
    'Well Location': 'Well Location',
}

p={
    'Sample Name': 'Sample Name',
    'Species': 'Species',
    'Library Type': 'Library Type',
    'Librray Concentration (ng/µl)': 'Client Assessed Concentration (ng/µl)',
    'Library Molarity (nM)': 'Client Assessed Molarity (nM)',
    'Library Ave Size (bp)': 'Average Library Size (bp)',
    'Library Volume (µl)': 'Client Assessed Volume (µl)',
    'Index1 or Pair Name': 'Index Name',
    'Index2 Name': 'i5 index Name',
    'i7 (Index 1) Sequence': 'i7 Index Sequence',
    'i5 (Index 2)_workflow_a': 'i5 Index Sequence',
    'Targeted read-pairs for Pool (millions)': 'Requested Number of Reads (M)',
    'Tube Label or External Barcode': '',
    '2D Rack Holder': '2D Barcode',
    'Well Location': 'Well Location',
}

atac={'i7 index_b (ATAC)': '',
    'i7 index_c (ATAC)': '',
    'i7 index_d (ATAC)': ''}
