### ISSUE TITLE
CLE Lab: Sample ingest

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#451]
For CLE, ingest will compose of two steps.

1. ~~Trim a CSV ingest file down to only samples listed that do not currently exists.~~
2. Do the actual ingest with the newly created trimmed-down list.

This ticket is for part 2.

~~To be completed after https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/450~~

Do work here for this ticket: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/225

**Comment by abohanno** [comment]
Hi All, got confirmation yesterday that the CoPath dashboard is exportable. This will be what we use as our import sheet for sample ingest into ESP. I will work on getting access to this dashboard so that I can get you an example of what the exported file will look like.

**Comment by abohanno** [comment]
Hi All,
[data.xlsx](https://github.com/user-attachments/files/17547304/data.xlsx)

Here is an exported example of what we are able to get from our CoPath dashboard. You can see that I was able to filter this for samples that were accessioned on or after 10/26. That's likey to be the best that we can do for getting this filtered down. We may need to still have some sort of "checker" script that makes sure we aren't accessioning a sample for the second time...

**Comment by abohanno** [comment]
Hi All,

Here is the list of procedures in CoPath sorted by CLE assay:

**SOMA**
Cortical Malformations and Epilepsy Panel V4
Inborn Errors of Immunity Panel V4
Maffucci Syndrome Panel V4
McCune Albright Syndrome V4
Nevus Panel V4
PIK3CA-Related Overgrowth Spectrum Disorders Gene Panel – Focused V4
PIK3CA-Related Overgrowth Spectrum Disorders Gene Panel – Comprehensive V4
Rasopathies Panel V4
Somatic Overgrowth Panel V4
Somatic Undergrowth Panel V4
Vascular Anomalies Panel V4
Custom Mosaicism Disorders Gene Panel – Focused V4
Custom Mosaicism Disorders Gene Panel – Comprehensive V4

**IDT Germline Exome**
Whole Exome Sequencing
Complement-mediated Renal Disease panel
Alport Syndrome panel
Cystic disease and Nephronophthisis panel
Nephrotic Syndrome and Focal Segmental Glomerulosclerosis panel
Custom Renal Diseases Gene Panel
Cardiac Diseases Gene panel (core or expanded)
Arrhythmia panel (core or expanded)
Brugada Syndromes (core or expanded)
Catecholaminergic Polymorphic Ventricular Tachycardia
Long QT Syndromes panel (core or expanded)
Cardiomyopathy panel (core or expanded)
Arrhythmogenic Right Ventricular Cardiomyopathy panel (core or expanded)
Dilated Cardiomyopathy panel (core or expanded)
Hypertrophic Cardiomyopathy panel (core or expanded)
Familial Thoracic Aortic Aneurysm and Dissection panel (core or expanded)
Custom Cardiac Diseases Gene Panel
Atypical Diabetes and ER Stress Disorders Gene Panel
Endoplasmic Reticulum Stress Disorders Panel
Hyperinsulinism Panel
Permanent Neonatal Diabetes Mellitus (PNDM) Panel
Monogenic Diabetes and MODY Panel
Custom Atypical Diabetes and ER Stress Disorders Gene Panel
CUSTOMIZED SET

**MyeloSeq**
MyeloSeq Molecular Diagnostics

**ChromoSeq**
ChromoSeq Molecular Diagnostics

**GatewaySeq**
GatewaySeq Molecular Diagnostics

**cGS**
Whole Genome Sequencing

We can discuss this list in detail at another meeting. Let me know if you have questions before then.

**Comment by tim-snyder-wustl** [comment]
The assays:

- IDT Tumor Normal
- UDN

are done by CLE but are not handled by the Copath log, so these will need to be entered manually.

Will need a manual entry option anyway in case Copath is down, etc.

**Comment by abohanno** [comment]
MRN List is officially part of the clinical dashboard! We should have what we need to get started in earnest on accessioning.

**Comment by abohanno** [comment]
[Updated_MRN_List_CLE_Dashboard.xlsx](https://github.com/user-attachments/files/17833755/Updated_MRN_List_CLE_Dashboard.xlsx)

**Comment by LMT337** [comment]
Create FS DB for Assay tracking/lookup

**Comment by LMT337** [comment]
Make all Entity fields un-required

**Comment by LMT337** [comment]
CLE Assay mapping tsv[cle_assay_mappying.xls](https://github.com/user-attachments/files/18158518/cle_assay_mappying.xls)

**Comment by LMT337** [comment]
Collection date format? 
MRN List format? 
Which columns require value in every row? 
what to do if assay is none?  Script Error? 
What should notes column correspond to, if any?  Currently adding Sent Comment.

**Comment by LMT337** [comment]
Flip collection date to match CLE
Andy follow up about MRN seperator
Remove autofill dropdown from  columns that script fills in, leave the ones like Billing and User, date etc...
Script fail if values missing in required columns
assay not exact match could be upper/lower, fix assay test

determine next step on Specimen, auto populate field using Entity. 
Tissue/FFPE/Cell Pellets -> Manual
Blood/Bone Marrow/Buccal Swab  -> QiaCube
DNA -> Assessment 

Leave Notes column Blank

**Comment by LMT337** [comment]
Add exceptions column, that syncs with protocol action.

For Blood/Bone Marrow (possibly Buccal) if collection date older than 15 days. 
Andy will send me comment to add to Exception column.

**Comment by abohanno** [comment]
From Feiyu:
The pipe “|” separator in MRN_list is ok for us. If that pipe is not desired/preferred by LIMS and could cause potential programming issue, then comma “,” can be used if the output sample sheet by L7-ESP is tab-delimited.

**Comment by LMT337** [comment]
flip date to match Entity
Map speciman type from co-path to CLE specimen type, Andy will update ticket with mapping. 
Andy send list of columns that require a value
Fail on assay look up returns None

**Comment by abohanno** [comment]
Hi Lee,

See the following document for the specimen type mapping. I went all the way back to the beginning of November. I can't guarantee that I got them all, but it should be most.

Thanks,
Andy

[Specimen Type Mapping.docx](https://github.com/user-attachments/files/18511967/Specimen.Type.Mapping.docx)

**Comment by abohanno** [comment]
I think that most exceptions for sample intake/accessioning will be handled through JIRA issues and will be sorted out prior to accessioning into LIMS. The one that I think we might want to have auto-fill would be:

Specimen is not received or will not be extracted within 60 days of the date of collection for blood, bone marrow, or buccal swabs.

This window was 15 days when we started LIMS development, but was recently updated after a review of assessment data by Shelly.

**Comment by abohanno** [comment]
For what columns we would like to be required at accessioning, I am not sure I was looking at your most up-to-date version of the protocol. If we are going to be ingesting using the dashboard export as a template, I would think the only things that we wouldn't care about being required would be the following columns:

Sent Date
Sent Comment
Received Comment 
Accession Date

**Comment by LMT337** [comment]
Specimen mapping spreadsheet: 
[specimen_mapping.xls](https://github.com/user-attachments/files/18550985/specimen_mapping.xls)

determine next step on Specimen, auto populate field using Entity.
Tissue/FFPE/Cell Pellets -> Manual
Blood/Bone Marrow/Buccal Swab -> QiaCube
DNA -> Assessment

Specimen Type values: 
['Bone Marrow', 'Buccal Swab', 'DNA', 'FFPE', 'FNA Smear', 'Fresh Tissue', 'Peripheral Blood']

MANUAL = 'CLE Lab: Manual Extraction'
AUTOMATED = 'CLE Lab: Automated Extraction'
ASSESSMENT = 'CLE Lab: Specimen Assessment'

{'Bone Marrow': AUTOMATED, 
'Buccal Swab': AUTOMATED, 
'DNA': ASSESSMENT, 
'FFPE': MANUAL, 
'FNA Smear': MANUAL , 
'Fresh Tissue': MANUAL, 
'Peripheral Blood': AUTOMATED}

Should Cell Pellets be tracked?

**Comment by LMT337** [comment]
Tag entities?

**Comment by LMT337** [comment]
Andy follow up about Cell Pellets and Tagging

**Comment by abohanno** [comment]
Hi Lee,

updated sample mapping attached. I dug all the way back to the summer for more weird entries and found several more. This should hopefully cover all the bases now. If not, we may have a few more things to add later on. New entries are in RED.

[Specimen Type Mapping.docx](https://github.com/user-attachments/files/18576020/Specimen.Type.Mapping.docx)

Thanks,
Andy

**Comment by LMT337** [comment]
Updated specimen mapping added to Firestore. 

[specimen_mapping.xls](https://github.com/user-attachments/files/18576313/specimen_mapping.xls)

**Comment by LMT337** [comment]
@abohanno item for tomorrow, should we be checking at ingest if a sample with the same name/assay/tissue type already exists in LIMS?

**Comment by LMT337** [comment]
Fail sample if duplicate, check these fields: Accession Name, Assay, Patient Name
Double check these columns, value required on every row: 
['Accession Number', 'MRN', 'MRN List', 'Specimen Type']

**Comment by abohanno** [comment]
Batch ID String for auto tagging = Batch YYYYMMDD (Batch 20250131)

**Comment by abohanno** [comment]
Tried ingesting using the protocol on sandbox and a file that i downloaded from the CoPath dashboard. Received the following error:

Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/cle_receive_specimen.py", line 149, in <module>
    ebase.SESSION.put('/api/samples', json={'samples': payload})
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/esp/base.py", line 251, in _
    return func(self, endpoint, **kwargs)
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/esp/base.py", line 218, in _
    raise AssertionError(
AssertionError: Response from server (400) different from expected (200, 201, 202)

SERVER ERROR: None

SERVER TRACEBACK: None
{
 "units": "ms"
 "approximate_execution_time": 2751.367144
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["PUT /api/samples", 1, 467.077082, 467.077082, 467.077082, 467.077082, 1]
  ["GET /api/sample_sheets/:uuid/bulk", 1, 294.935849, 294.935849, 294.935849, 294.935849, 1]
  ["GET /api/sample_type_definitions/:uuid", 1, 259.357271, 259.357271, 259.357271, 259.357271, 1]
  ["GET /api/samples", 1, 229.73063, 229.73063, 229.73063, 229.73063, 1]
  ["GET /api/sample_sheets/:uuid", 1, 201.661098, 201.661098, 201.661098, 201.661098, 1]
  ["GET /api/files/:uuid", 1, 119.931906, 119.931906, 119.931906, 119.931906, 1]
 ]
}

Also attaching ingest sheet for review.

[ESP_Ingest_12925_Edited.xlsx](https://github.com/user-attachments/files/18592300/ESP_Ingest_12925_Edited.xlsx)

**Comment by abohanno** [comment]
The dates in the sheet look like they're messed up. Not sure if that was the problem or not.

**Comment by LMT337** [comment]
@abohanno Taking a look was able to duplicate on local dev instance.

**Comment by LMT337** [comment]
Issue due to Entity field Collection Date using wrong format, fixed on Sandbox.

**Comment by LMT337** [comment]
- [x]  Create Custom Query w/L7 to check for duplicate samples with: Accession Name, Assay, Patient Name

**Comment by abohanno** [comment]
New error attempting to ingest 16 SOMA specimens:

{
 "units": "ms"
 "approximate_execution_time": 3350.054342
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["GET /api/sample_sheets/:uuid/bulk", 1, 341.201217, 341.201217, 341.201217, 341.201217, 1]
  ["GET /api/sample_sheets/:uuid", 1, 236.857084, 236.857084, 236.857084, 236.857084, 1]
  ["GET /api/files/:uuid", 1, 118.368399, 118.368399, 118.368399, 118.368399, 1]
 ]
}

Attaching ingest sheet for review

[AB_ESP_Ingest_SOMA_20250131.xlsx](https://github.com/user-attachments/files/18623256/AB_ESP_Ingest_SOMA_20250131.xlsx)

Also, I think that we can drop the "Received By" column in the first protocol of sample ingest. This gets recorded on the req sheet, so we can review there if necessary. I just think it will be too time consuming to do this in ESP. Samples are taken in by many people at many different times throughout the day. You would almost need all the req sheets in front of you to do this...

**Comment by LMT337** [comment]
@abohanno these specimen types don't map to our speciman database: 
FFPE (OSC#: S24-2539)
FFPE (OSC#: S23-3633)
FFPE (OSC#: S24-215)
FFPE (OSC#: TS23-2164)

which is because I'm using this value: FFPE (OSC#: xxxx-xxxx)

I see now the x's were just a place holder.  I'll update to handle this instance and fix the error message which wasn't reporting in ESP for some reason. The script did catch it though, that's why it failed which is a good sign.

**Comment by LMT337** [comment]
Deployed fix for  FFPE (OSC#: xxxx-xxxx) and removed Received By protocol column.

**Comment by LMT337** [comment]
- [x] MRN is converted to float by Pandas, convert to string
- [x] Add billing account tag/batch tag

Andy checking on Cost Center Entity field.

**Comment by LMT337** [comment]
Add GB to Entity based on Assay, @abohanno Andy will provide mapping. Add it to Firestore for look up.

**Comment by abohanno** [comment]
![Image](https://github.com/user-attachments/assets/7716042f-9add-42da-9b8b-d0bb6b7e05dd)

**Comment by LMT337** [comment]
Gb assingment working, follow up on edge cases
Duplicate check working, need to best implementation for ingest.

**Comment by LMT337** [comment]
- [x]  Add column that appears for dups with same Accession Number/Assay
- [x]  Mapp Assay to billing fields/Add to FS/Fill in Billing Value in WS
- [x]  Update Gb to check for tumor/normal in Accession Number for IDT Tumor-Normal Exome assays

**Comment by abohanno** [comment]
Just to mark down what I've been sending you in Slack...

Error: No assay found for myeloseq-mrd_molecular_diagnostics

Error: No assay found for dian_trial

Error: No specimen found for whole_blood_-_screen

Error: No specimen found for smear_for_gatewayseq

**Comment by abohanno** [comment]
Also got this one:

Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/cle_receive_specimen.py", line 140, in <module>
    cle_ingest_protocol.df['Exceptions'] = cle_ingest_protocol.df['Collection Date'].apply(specimen_exceptions) # Add Exceptins comment if specimen older than 60 days
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/pandas/core/apply.py", line 1088, in apply
    return self.apply_standard()
  File "/opt/l7esp/data/extensions/client/lib/python3.9/site-packages/pandas/core/apply.py", line 1143, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "/opt/l7esp/data/content/pipelines/scripts/cle_receive_specimen.py", line 111, in specimen_exceptions
    collection_date = datetime.strptime(collection_date, '%Y-%m-%d')
  File "/opt/l7esp/data/extensions/client/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/l7esp/data/extensions/client/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
{
 "units": "ms"
 "approximate_execution_time": 2225.896476
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["GET /api/sample_sheets/:uuid/bulk", 1, 357.215849, 357.215849, 357.215849, 357.215849, 1]
  ["GET /api/sample_sheets/:uuid", 1, 244.694678, 244.694678, 244.694678, 244.694678, 1]
  ["GET /api/files/:uuid", 1, 112.355402, 112.355402, 112.355402, 112.355402, 1]
 ]
}

**Comment by abohanno** [comment]
I have looked at the ingest sheet multiple times. I don't see a problem with the collection dates that the error references. Not sure what the problem is...

**Comment by abohanno** [comment]
Error: No assay found for rapid_whole_genome_sequencing

This will need to update to the above from "whole genome sequencing" in the assay mapping document

**Comment by LMT337** [comment]
- IDT Tumor-Normal Exome present on Entity for Assay selection, no mapping values in Firestore Assay DB, checking with Andy to update DB.

**Comment by abohanno** [comment]
🛑Error: No assay found for pik3ca-related_overgrowth_spectrum_disorders_gene_panel_-_comprehensive_v4🛑

This will need added to the sample mapping list under SOMA procedures

**Comment by LMT337** [comment]
Added to FS: 
pik3ca-related_overgrowth_spectrum_disorders_gene_panel_-_comprehensive_v4 : SOMA

**Comment by LMT337** [comment]
Billing account mapping: 

[Billing Accounts for CLE.xlsx](https://github.com/user-attachments/files/18801630/Billing.Accounts.for.CLE.xlsx)

**Comment by LMT337** [comment]
Required functions completed, testing worksheet: 
[CLE_Ingest_Testing](https://app.smartsheet.com/sheets/25c9cqMJJHHR9XfMQ7qhpfFqqXmPRhQm4rRxv2F1?view=grid)

**Comment by abohanno** [comment]
Hey Lee,

Working on a few of the things we talked about:

- It looks like they added a new specimen type: BLOOD MS MRD so I will need to add this to the specimen mapping document
- I was able to create two identical entities and submit them to ingest. I was able to complete the ingest pipeline script as well. We should probably make sure we can't do that.
- The script correctly assigned sequencing space based upon assay.
- Billing account was only assigned for GPS assays (SOMA, IDT Germline Exome). It was not assigned for Molecular Oncology assays (MS).
- I received a save error trying to submit my newly ingested samples to the next workflow. It tells me that I need to save before I can submit, but the save has already been committed and cannot be done again.

**Comment by abohanno** [comment]
I submitted the same entity again and ingested it again, so I'm not sure that the duplicate check is working. Ran into the same error at submit to next workflow. I might be stuck if I can't move from from workflow to workflow.

**Comment by LMT337** [comment]
Looks like it worked because you can now see the Duplicate column in the worksheet with the duplicate Assay value.  I didn't add the sample name since it's implied because of the row it's on: 

<img width="909" alt="Image" src="https://github.com/user-attachments/assets/b75712ad-2e5d-4d03-8e94-d10276825701" />

**Comment by abohanno** [comment]
Ok, I was thinking that this would be more of a failed ingest thing rather than just a column value. I would be worried that this will get missed all the time. Is it possible to make this a hard fail?

**Comment by LMT337** [comment]
- [ ] When Duplicate sample returns True, Fail sample in worksheet. 
- [ ] BLOOD MS MRD maps to Peripheral Blood
- [ ]  Create shared docs for specimen and assay tracking
- [ ]  Update FS with assay specific mapping for chromoseq billing

**Comment by abohanno** [comment]
Another thing to add to the Procedure Name document:

🛑Error: No assay found for custom_mosaicism_disorders_gene_panel_-_focused_v4🛑

**Comment by abohanno** [comment]
Another thing to add to the Specimen Type document:

🛑Error: No specimen found for skin_biopsy_ms🛑

**Comment by abohanno** [comment]
Billing account did not appear for MyeloSeq samples at ingest. It does now appear for ChromoSeq samples!

**Comment by abohanno** [comment]
Hi Guys, received the "save workbook before sending samples to the next workflow" error again even though the sheet has been saved and it cannot be saved again. Also the billing account for the lone MyeloSeq sample I was ingesting did not populate.

**Comment by abohanno** [comment]
Looks like the "Sequencing Gb" and "Sequencing Gb Total" might be busted. I added the same entity I created yesterday for accessioning and it assigned 0Gb. Not sure if this is because it assigned the space for it yesterday and won't do it again, or if it has to do with us correcting the name of the assay. In better news, the assay for MyeloSeq is now correctly spelled!

**Comment by abohanno** [comment]
Can't remember what we decided on UDN specimen ingest. Should I avoid trying to use the pipeline script altogether and just enter the info manually?

**Comment by abohanno** [comment]
Just received the following from Shelly:

At some point in the future, our accessioning will look more like this

MyeloSeq MRD   25WML-056MG001
MyeloSeq    25WML-056MG002
GatewaySeq  25WML-056MG003
ChromoSeq    25WML-056MG004
Constitutional NGS   25WMC-056GX001

Go live is April 2026, so we have plenty of time, but just something we want to be sure is accounted for changing at some point as we go live into LIMS.

**Comment by abohanno** [comment]
I think I know the answer to this, but is the accessioning workflow dependent upon the accession number being in the W25-1234 format?

**Comment by abohanno** [comment]
@LMT337 sorry, I forgot to tag you in my comments a few minutes ago. See above..

**Comment by abohanno** [comment]
Hi @LMT337 It looks like billing accounts are changing as well... I was unaware that any of this was happening!!!!

![Image](https://github.com/user-attachments/assets/23dfc5a3-0f1c-401c-b469-60ad3ff3e8cf)

**Comment by LMT337** [comment]
- [ ] Error checking for dates, return human readable message
- [ ] Fail sample if duplicate in addition to showing hidden Duplicate column
- [ ] Delete Specimen type from Automated Extraction Protocol/Manual

**Comment by abohanno** [comment]
I have updated the specimen mapping, billing mapping, and assay mapping documents with the items we discussed today

**Comment by abohanno** [comment]
Hi @LMT337,
Still receiving an error related to the PIK3CA procedure names:

Error: No assay found for pik3ca-related_overgrowth_spectrum_disorders_gene_panel_-_comprehensive_v4🛑
{
 "units": "ms"
 "approximate_execution_time": 3412.051409
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["GET /api/sample_sheets/:uuid/bulk", 1, 209.135002, 209.135002, 209.135002, 209.135002, 1]
  ["GET /api/sample_sheets/:uuid", 1, 144.756486, 144.756486, 144.756486, 144.756486, 1]
  ["GET /api/files/:uuid", 1, 116.715901, 116.715901, 116.715901, 116.715901, 1]
 ]
}

**Comment by abohanno** [comment]
These were the procedure names that showed up with the weird string of characters ('@ or something like that) instead of a "-". I fixed it in the mapping document but it still isn't working.

**Comment by abohanno** [comment]
Also just realized that when we first provided you with the list of procedure names, Meagan had a whole bunch of the IDT Germline Exome ones listed with (Core or Expanded) at the end. These show up as separate procedure names in CoPath. I have corrected the assay mapping document for this.

**Comment by abohanno** [comment]
added the following to the specimen mapping document:

Bone Marrow Fresh Core CS
Fibroblast
DNA extracted from blood
DNA from tissue of the face
Extracted DNA from blood
DNA from blood
Whole Blood - SCREEN
Smear for GatewaySeq
Tissue for GatewaySeq (XXX-XXXXX)
PB DNA MS
Bone Marrow FFPE Core MS
FFPE Tissue MS
Skin Biopsy MS
DNA from fibroblasts
DNAfrom tissue - this one really concerns me....
Mucosa
Periosteum
Other-DNA extracted from skin biopsy
DNA
DNA from skin
DNA from buccal
Other-DNA from tissue

@LMT337 I have seen enough truly unique shit that I didn't even add to this list that I am almost certain now that the accessioners have some leeway to add whatever they want as the specimen type. This is problematic and we will need to discuss. I can show the examples of the really oddball stuff if you want to see them.

**Comment by abohanno** [comment]
@LMT337,
Any idea why ESP would stop assigning sequencing Gb partway down a worksheet? It assigned 9Gb for one SOMA but 0 for another.

http://sandbox5.wucon.wustl.edu:11702/#/lims/worksheet/de977bf8-dbde-449e-ad0b-af74198b9960

**Comment by LMT337** [comment]
re-name extractions to additional extractions
check gb error - not assigning to all samples

**Comment by LMT337** [comment]
Add CoPath Accession number to Entities, capture on ingest, Accession Number is an internal value that may need to be processed at a later date.

**Comment by abohanno** [comment]
@LMT337 and @tim-snyder-wustl,

Recently bumped sequencing Gb back up to 175Gb from 160Gb. I changed this using the new webtools mapping app!!!

**Comment by abohanno** [comment]
sorry, that's for cGS samples....

**Comment by LMT337** [comment]
@abohanno I found out why one of the Gb assignment was failing: 
Buccal Swab	2025-02-23	2025-03-18	VASCULAR ANOMALIES PANEL V4	SOMA

We con't have a Buccal Swab/SOMA mapping in the db, do we need one?

**Comment by abohanno** [comment]
Hi @LMT337,

Yes we should have one. See the following image for a list of validated specimen types for each assay. This does not mean that other types cannot move through a particular assay, just that it would be an exception.

![Image](https://github.com/user-attachments/assets/fbe28d67-aede-4c92-9ddc-716566ad0b3d)

**Comment by LMT337** [comment]
@abohanno cool, I made a spreadsheet out of that image.  Attaching it here.  
The way it works, is that it checks if theres a gb assay_specimen and assigns that value if it exists, if not, it checks for assay value, if that doesn't exist it assigns 0. 
Do we need a default value for SOMA if it's not found?  Or do we need specific assay specimen mappings for these?  Here's what's in the db right now: 

cgs	175
chromoseq	275
gatewayseq	8
idt_germline_exome	25
idt_tumor-normal_exome_normal	30
idt_tumor-normal_exome_tumor	70
myeloseq	30
soma_ffpe	12
soma_fresh_tissue	9

There isn't a soma mapping so it's not assigning a value if soma_buccal isn't found, it's defaulting to 0. 

[cle_gb_assays.csv](https://github.com/user-attachments/files/19322649/cle_gb_assays.csv)

**Comment by LMT337** [comment]
- [ ]  mapping for idt_germline_exome and Aliquot Amount, set up mapping based on procedure from copath and set aliquot amount. (Andy will send mapping, need to update webtools for mapping updates)

**Comment by abohanno** [comment]
IDT Germline Exome Aliquot Mapping:

![Image](https://github.com/user-attachments/assets/5c352200-7871-4a35-8885-61a67c8b1e6c)

**Comment by LMT337** [comment]
Check duplicate function, not calling all dups, showing modal when samples reviewed.
