### ISSUE TITLE
CLE Lab: Extraction / Speciment Assessment Workflow Revisions

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#493]
Make revision based on Monday 10/28 working session.

**Comment by billtell** [comment]
### Setup Protocol

- [x] Sample Name -> Accession Number
- [x] Accession Number populates from entity
- [x] Remove `Next Step`
- [x] Tissue Type -> Specimen Type
- [x] Use a Autofill onchange that does not overwrite existing values :  `onchange_autofill_no_overwrite()`
- [x] Unhide QIACube columns

**Comment by billtell** [comment]
### Sample Protocol

- [x] Unrequire and hide the following columns
-  Volume | Concentration | Yield | 260/280 | 260/230 |  Cost Center
- [x] Remove `Note` column
-  Muted `Notes` value.  Comes with Sample protocol for free? How to handle
- [x] Add Next Step column

**Comment by billtell** [comment]
For CLE Genomic DNA
Specimen Type -> Sample Type or keep it Specimen Type

**Comment by billtell** [comment]
### Datalinks added
```
CLE Lab: DNA Extraction':     
    Accession Number: "{{ entity_value('Accession Number', generation=-1) or '' }}"
    Assay: "{{ entity_value('Assay', generation=-1) or '' }}"
    Sample Type: "{{ entity_value('Specimen Type', generation=-1) or '' }}"
    MRN: "{{ entity_value('MRN', generation=-1) or '' }}"
```

**Comment by abohanno** [comment]
[QubitData_18-11-2024_12-36-15.csv](https://github.com/user-attachments/files/17804125/QubitData_18-11-2024_12-36-15.csv)

Annotated Qubit Flex File

**Comment by abohanno** [comment]
[SOMA270_101023_KLSNANODROP.xlsx](https://github.com/user-attachments/files/17804148/SOMA270_101023_KLSNANODROP.xlsx)

Annotated Nanodrop file. (I converted this from xml to xlsx, I think this should be easy enough for us to do each time)

**Comment by abohanno** [comment]
Hi All,

Was doing some testing today. Created entities and worked through automated extraction with a few samples just fine. Got to specimen assessment and received an error during the pipeline script. I believe the error has something to with the following:

•	Pipeline script error: Volume threshold not defined for specimen type Buccal Swab and extraction method Automated

I had a MyeloSeq sample in the group of six that I listed as buccal swab. It looks like maybe the script didn't like it. Let me know if that's not the issue and it had to do with formatting or something. We do perform most buccal swab extractions on the QIACube now with an expected volume of ~100uL per reaction if this info needs to be added to the script.

My Project/Experiment was AB_CLE_Test_20250124 but it looks the assessment worksheet might be named CLE Lab: Specimen Assessment?

Thanks,
Andy

**Comment by abohanno** [comment]
Hi All,

Got a similar error as my first test when I took my newly ingested (thanks Lee) MyeloSeq samples into assessment.

Traceback (most recent call last):
  File "/opt/l7esp/data/content/pipelines/scripts/cle_specimen_assessment.py", line 189, in <module>
    assessed_data = assess_pass_fail(ingest_protocol, qubit_file_dict, nanodrop_file_dict)
  File "/opt/l7esp/data/content/pipelines/scripts/cle_specimen_assessment.py", line 125, in assess_pass_fail
    raise ValueError(
ValueError: Volume threshold not defined for specimen type Peripheral Blood and extraction method Automated
{
 "units": "ms"
 "approximate_execution_time": 1113.173037
 "call_headers": ['API', '#Calls', 'Cumulative', 'Min', 'Max', 'Mean', '#UniqueEndpoints']
 "calls": [
  ["GET /api/sample_sheets/:uuid/bulk", 1, 328.3664, 328.3664, 328.3664, 328.3664, 1]
  ["GET /api/files", 2, 251.803566, 124.326353, 127.477213, 125.901783, 2]
  ["GET /api/sample_sheets/:uuid", 1, 216.822754, 216.822754, 216.822754, 216.822754, 1]
 ]
}

It still looks like it did not assign any of the values from the ingested files. We can discuss and make sure that I don't have something formatted improperly.

**Comment by abohanno** [comment]
Was able to complete the ingest of the assessment data with help from Bill. I did receive a new error when I tried to save and submit to next workflow:

Failed to process action Sync Instrument Data of protocol CLE Lab: Specimen assessment Review in worksheet AV_CLE_Test_20250129 (473527f2-2925-4a4e-a087-78efdb218e7c): '131955'

I wasn't sure what it did at first but I think I figured out it failed to sync the concentration and yield data back to the CLE specimen entity type. I was able to proceed to dilutions.
